TrainerClientADOnet/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainerClientADOnet.Models.DAO;
using TrainerClientADOnet.Models.DTO;
using TrainerClientADOnet.Utilities;

namespace TrainerClientADOnet.Controllers
{
    public class MealController : Controller
    {
        MealDAO mealDAO = new MealDAO();
        static MealDTO[][] mealDescriptions = new MealDTO[3][];

        // GET: Training/Details/5
        [Authorize(Roles = Utility.CLIENT_ROLE)]
        public ActionResult Details(int id)
        {
            var meal = mealDAO.GetById(id);
            if (meal != null)
            {
                return View(meal);
            }
            else
            {
                return View("Error");
            }
        }

        //ok
        // GET: Meal/Create
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Create(int id, int mealTypeId, DateTime date, int programId, DateTime monday)
        {
            var meal = GetById(id, mealTypeId);  
            if (meal != null)
            {
                ViewBag.SelectedMonday = monday;
                return View(meal);
            }
            else
            {
                return View("Error");
            }
        }
        //OK-treba da ga potrazi u onom nizu i kada ga nadje, treba njega vratiti
        private MealDTO GetById(int id, int mealTypeId)
        {
            for (int j = 0; j < 7; j++)
            {
                if (((MealDTO)(mealDescriptions[mealTypeId-1][j])).Id == id) { return mealDescriptions[mealTypeId-1][j]; }
            }
            return null;
        }

        //OK
        // POST: Meal/Create
        [HttpPost]
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Create(DateTime date, int programId, DateTime monday, FormCollection collection)
        {
            try
            {
                int mealTypeId = int.Parse(collection["MealTypeId"]);
                string description = collection["Description"];
                int recurring = int.Parse(collection["Recurring"]);

                DateTime startTime = date;
                //ovo sedmicno gleda
                for (int j = 1; j <= recurring; j++)
                {
                    //U istom danu da nadodaje meal
                    int newId = mealDAO.Create(programId, mealTypeId, startTime, description);

                    startTime = startTime.AddDays(7);
                }

                DateTime sunday = monday.AddDays(6);
                return RedirectToAction("MealPlanForProgram", new { programId = programId, monday = monday, sunday = sunday });
            }
            catch
            {
                return View();
            }
        }

        // GET: Meal/Edit/5
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Edit(int id, DateTime monday)
        {
          
                var meal = mealDAO.GetById(id);
                if (meal != null)
                {
                meal.StartTime = meal.StartTime.Date;
                ViewBag.SelectedMonday = monday;
                return View(meal);
                }
                else
                {
                    return View("Error");
                }
        }

        //OK
        // POST: Meal/Edit/5
        [HttpPost]
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Edit(int id,  DateTime monday, int mealTypeId, FormCollection collection)
        {
            try
            {
                int programID= int.Parse(collection["ProgramId"]);
                string description = collection["Description"];
                int number = mealDAO.Edit(id, description);
                return RedirectToAction("MealPlanForProgram", new { programId = programID, monday = monday });
            }
            catch
            {
                return View("Error");
            }
        }


        //NADJEM sve obroke koji imaju ovaj program id - iz BAZE  I  pripadaju opsegu datuma u ovoj sedmici
        // GET: Meal/MealPlanForProgram/5
        public ActionResult MealPlanForProgram(int programId, DateTime monday)
        {
            var sunday = monday.AddDays(6);
            var model = mealDAO.getByProgram(programId, monday, sunday);
            model = model.Where(t => t.StartTime.Date >= monday.Date && t.StartTime.Date <= sunday).ToList();
            var orderedMeals = PutMealsInOrder(model, monday);
            ViewBag.Meals = orderedMeals;
            ViewBag.SelectedMonday = monday;
            return View();
        }
        /*reda obroke tako da meals[1] je dorucak; meals[2] je rucak...
         a dane postavlja tako da krece od ponedeljka-nedelje. tj/ [0]-[6]*/
        private MealDTO[][] PutMealsInOrder(List<MealDTO> model, DateTime monday)
        {
            MealDTO emptyMeal = new MealDTO();
            
            for (int i = 0; i < 3; i++)
            {
                mealDescriptions[i] = new MealDTO[7];
                for (int j = 0; j < 7; j++)
                {
                    emptyMeal = getMealById(i);
                    emptyMeal.StartTime = getDayOfTheWeekByIdAndWeek(j, monday);  //getDayOfTheWeekById(j);
                    //popunjavanje podacima iz baze
                    mealDescriptions[i][j] = (MealDTO)model.Where(m => i + 1 == m.MealTypeId)
                    .FirstOrDefault(m => m.StartTime.DayOfWeek == getDayOfTheWeekForId(j));
                    // inicijalizacija niza            
                    if (mealDescriptions[i][j] == null)
                    {
                        mealDescriptions[i][j] = emptyMeal;
                    }
                }
            }
            return mealDescriptions;
        }

        private DateTime getDayOfTheWeekByIdAndWeek(int j, DateTime monday)
        {

            if (j == 0) //pon
                return monday;
            else if (j == 1)
                return monday.AddDays(1);
            else if (j == 2)
                return monday.AddDays(2);
            else if (j == 3)
                return monday.AddDays(3);
            else if (j == 4)
                return monday.AddDays(4);
            else if (j == 5)
                return monday.AddDays(5);
            else //if (j == 6)
                return monday.AddDays(6); ;


        
            

        }

        private MealDTO getMealById(int i)  //NOT GOOD, jer je hard kodovano (ako se ubaci i obrok u bazu, vise treba da se popravi...)
        {
            if (i == 0)
                return new MealDTO("breakfast");
            else if (i == 1)
                return new MealDTO("lunch");
            else //if (i == 2)
                return new MealDTO("dinner");
        }
        private DateTime getDayOfTheWeekById(int j)
        {
            if (j == 0) //pon
                return Utility.GetThisWeekMonday();
            else if (j == 6)
                return Utility.GetThisWeekSunday();
            else if (j == 1)
                return Utility.GetThisWeekTuesday();
            else if (j == 2)
                return Utility.GetThisWeekWednesday();
            else if (j == 3)
                return Utility.GetThisWeekThursday();
            else if (j == 4)
                return Utility.GetThisWeekFriday();
            else //if (j == 5)
                return Utility.GetThisWeekSaturday();
        }
        private DayOfWeek getDayOfTheWeekForId(int j)
        {
            if (j == 0) //pon
                return DayOfWeek.Monday;
            else if (j == 6)
                return DayOfWeek.Sunday;
            else if (j == 1)
                return DayOfWeek.Tuesday;
            else if (j == 2)
                return DayOfWeek.Wednesday;
            else if (j == 3)
                return DayOfWeek.Thursday;
            else if (j == 4)
                return DayOfWeek.Friday;
            else //if (j == 5)
                return DayOfWeek.Saturday;
        }


    }
}

TrainerClientADOnet/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainerClientADOnet.Models.DAO;
using TrainerClientADOnet.Models.DTO;
using TrainerClientADOnet.Utilities;
using PagedList;

namespace TrainerClientADOnet.Controllers
{
    public class ProgramController : Controller
    {
        ProgramDAO programDAO = new ProgramDAO();
        GoalTypeDAO goalTypeDAO = new GoalTypeDAO();
        ProgramGoalTypeDAO programGoalTypeDAO = new ProgramGoalTypeDAO();

        //OK
        // GET: Program/Details/5
        public ActionResult Details(int id)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                program.ProgramType = Utility.setProgramType(program.IsMeal);
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

       
        //OK
        // GET: Program/Edit/5
        public ActionResult Edit(int id, int? clientId)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

        //todo:edit program
        // POST: Program/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, int? clientId, FormCollection collection)
        {
            var program = programGoalTypeDAO.GetById(id);
            try
            {
                //string name = collection["Name"];
               // int number = programDAO.Edit(id, name);

                //return RedirectToAction("Index");
                return RedirectToAction("AllProgramsOfClient", new { clientId = program.ClientId });
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Program/Delete/5
        public ActionResult Delete(int id, int? clientId)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                program.ProgramType = Utility.setProgramType(program.IsMeal);
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Program/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, int? clientId, FormCollection collection)
        {
            var program = programGoalTypeDAO.GetById(id);
            try
            {
                programDAO.Delete(id);

                return RedirectToAction("AllProgramsOfClient", new { clientId = program.ClientId });
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Program/AllProgramsOfClient/5
        public ActionResult AllProgramsOfClient(string clientId, int? page, int? goalTypeId)   //za slucaj da ide na 2.stranicu da i dalje zna da je uljucena pretraga iz combo boxa
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<ProgramGoalTypeDTO> pro = null;
            List<ProgramGoalTypeDTO> programs = programGoalTypeDAO.GetAllOfClient(clientId);
           // List<ProgramGoalTypeDTO> selectedPrograms=programs.Where(p=>p.Is)
            pro = programs.ToPagedList(pageIndex, pageSize);
            return View(pro);
        }

        //OK
        // GET: Client/CreateProgramForClient/5
        public ActionResult CreateProgramForClient(string clientId)
        {
            ProgramDTO program = new ProgramDTO();
            program.ClientId = clientId;
            program.StartTime = DateTime.Today;  
            program.EndTime = DateTime.Today;
            ViewBag.goalsItems = goalTypeDAO.GetAll();
            return View(program);
        }

        //ok
        // POST: Client/CreateProgramForClient/5
        [HttpPost]
        public ActionResult CreateProgramForClient(string clientId, FormCollection collection)  
        {
            try
            {
                
                int goalTypeId = int.Parse(collection["GoalTypeId"]);    
                DateTime startTime = DateTime.Parse(collection["StartTime.Date"]);
                DateTime endTime = DateTime.Parse(collection["EndTime.Date"]);
                string description = collection["Description"];
                bool isMeal= bool.Parse(collection["IsMeal"]);

                int id = programDAO.Create(clientId, goalTypeId, startTime, endTime, description, isMeal); 

               // return RedirectToAction("AllProgramsOfClient", new { clientId=client_id });
                return RedirectToAction("Details", new { id = id });   
            }
            catch
            {
                return View("Error");
            }
        }

    }
}

TrainerClientADOnet/Views/Meal/Create.cshtml
@model TrainerClientADOnet.Models.DTO.MealDTO
@using TrainerClientADOnet.Utilities;
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@{

    Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri);
    DateTime StartTime = DateTime.Parse(HttpUtility.ParseQueryString(uri.Query).Get("date").Trim());
    int programId = int.Parse(HttpUtility.ParseQueryString(uri.Query).Get("programId"));  
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>MealDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramId)
    @Html.HiddenFor(model => model.MealTypeId)



    @*
        <div class="form-group">
            @Html.LabelFor(model => model.MealTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MealTypeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MealTypeId, "", new { @class = "text-danger" })
            </div>
        </div>
    *@

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Recurring (weeks in same time)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Recurring", "1", htmlAttributes: new { @type = "number", @class = "form-control", @min = "1", @max = Utility.GetMaxTrainingReccuringTimeCreate(StartTime, programId) })
            @Html.ValidationMessage("Recurring", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
@{ 
     DateTime monday = ViewBag.SelectedMonday;
}
<div>
  
    @Html.ActionLink("Back to List", "MealPlanForProgram", new { programId = programId,  monday=monday}, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrainerClientADOnet/Views/Meal/Details.cshtml
@model TrainerClientADOnet.Models.DTO.MealDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MealDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @{Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri); }
    @Html.ActionLink("Back to List", "MealPlanForProgram", new { programId = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim() }, null)

</p>

TrainerClientADOnet/Views/Meal/Edit.cshtml
@model TrainerClientADOnet.Models.DTO.MealDTO
@using TrainerClientADOnet.Utilities;

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>MealDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.ProgramId)
    @Html.HiddenFor(model => model.MealTypeId)

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

@{ 
    var monday = ViewBag.SelectedMonday;
}
<div>
    @Html.ActionLink("Back to List", "MealPlanForProgram", new { programId = Model.ProgramId, monday=monday }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrainerClientADOnet/Views/Meal/MealPlanForProgram.cshtml
@model  TrainerClientADOnet.Models.DTO.MealDTO
@using System.Data;
@using TrainerClientADOnet.Models.DTO;
@using Microsoft.AspNet.Identity;
@using TrainerClientADOnet.Utilities;

<head>
    @section Scripts{
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
        <script type="text/javascript">

            function copyToClipboard(message) {
                var msg = message;
                console.log(msg);
                //use msg now
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val(msg).select();
                document.execCommand("copy");
                $temp.remove();
            };
        </script>
    }
</head>

@{
    var firstDay = DayOfWeek.Monday;
    var secondDay = DayOfWeek.Tuesday;
    var thirdDay = DayOfWeek.Wednesday;
    var fourthDay = DayOfWeek.Thursday;
    var fifthDay = DayOfWeek.Friday;
    var sixthDay = DayOfWeek.Saturday;
    var seventhDay = DayOfWeek.Sunday;

    var pickedWeekMondayDate = ViewBag.SelectedMonday;
    var pickedWeekTuesdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(1);
    var pickedWeekWednesdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(2);
    var pickedWeekFridayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(4);
    var pickedWeekThursdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(3);
    var pickedWeekSaturdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(5);
    var pickedWeekSundayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(6);
    //uri
    Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri);
    var programIdFromUri = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim();
    //ime i prezime klijenta:
    string fullName = Utility.GetFullNameByProgramId(int.Parse(programIdFromUri));

    var previousMonday = Utility.previousMonday(ViewBag.SelectedMonday);
    var nextMonday = Utility.nextMonday(ViewBag.SelectedMonday);
}
<h2>
    Meal plan for client
    <b>@fullName </b>
</h2>
@* Dugmad za prebacivanje na sledecu i prethodnu sedmicu *@
<button type="button" onclick="location.href='@Url.Action("MealPlanForProgram", "Meal", new { programId = programIdFromUri, monday = previousMonday })'">
    <img alt="Previous" title="New" src="~/Images/Button/left.png" style="width: 15px; height:20px">
</button>
<button type="button" onclick="location.href='@Url.Action("MealPlanForProgram", "Meal", new { programId = programIdFromUri, monday  = nextMonday })'">

    <img alt="Next" title="New" src="~/Images/Button/right.png" style="width: 15px; height:20px">
</button>

@if (@pickedWeekMondayDate.ToString("MMMM").Equals(@pickedWeekSundayDate.ToString("MMMM")))
{//prikaz: July 20 - 27, 20
    <h3>
        @pickedWeekMondayDate.ToString("MMMM") @pickedWeekMondayDate.ToString("dd") - @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yy")
    </h3>
}
else //prikaz: July 27 - August 02, 20
{
    if (@pickedWeekMondayDate.ToString("yy").Equals(@pickedWeekSundayDate.ToString("yy")))
    {
        <h3>
            @pickedWeekMondayDate.ToString("MMMM")  @pickedWeekMondayDate.ToString("dd") - @pickedWeekSundayDate.ToString("MMMM") @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yy")
        </h3>
    }
    else //prikaz: December 27, 2020 - Januar 02, 2021
    {
        <h3>
            @pickedWeekMondayDate.ToString("MMMM")  @pickedWeekMondayDate.ToString("dd"), @pickedWeekMondayDate.ToString("yyyy") - @pickedWeekSundayDate.ToString("MMMM") @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yyyy")
        </h3>
    }
}
<style>
    td.actionCreate {
        zoom: 1;
        filter: alpha(opacity=0);
        opacity: 0;
    }

    td:hover {
        zoom: 1;
        filter: alpha(opacity=100);
        opacity: 1;
    }

    td.actionsAloneTraining {
        background-color: #ffebcc;
        filter: alpha(opacity=0);
    }
    </style>

@functions{
    public HtmlString cell(MealDTO meal)
    {
        Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri);
        var programIdFromUri = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim();
        var monday = ViewBag.SelectedMonday;
        String result = "<td>" + @meal.Description;
        String create = (@Html.ActionLink("+", "Create", new { id = meal.Id, mealTypeId = meal.MealTypeId, date = meal.StartTime, programId = programIdFromUri, monday = monday }, new { @class = "btnCreate" })).ToString();
        String edit = (@Html.ActionLink("Edit", "Edit", new { id = meal.Id,  monday = monday, date = meal.StartTime, mealTypeId = meal.MealTypeId, programId = meal.ProgramId })).ToString();
        // String Details= ()
        String details = (@Html.ActionLink("Details", "Details", new { id = meal.Id, date = meal.StartTime, mealTypeId = meal.MealTypeId, programId = programIdFromUri })).ToString();

         var description = meal.Description;
        var image =@Url.Content("~/Images/Button/cb5.png");
       //     description=description.TrimEnd();
        String copy = " <button type=\"button\" id=\"copyButton\" runat=\"server\" onClick=\" copyToClipboard(\'"+description+"\'); \" style=\"background-color: Transparent; border: none;\" >  <img src=\""+image+"\" style=\"height:20px;width:15px;color:blue\" title=\"Copy to clipboard description\" /> </button>"; // @* *@



        if (User.IsInRole(Utility.TRAINER_ROLE))
        {
            if (meal.Id > 0)
            {
                return new HtmlString(result + edit + copy + "</td>");
            }
            else
            {
                result = "<td class=\"actionCreate\">" + @meal.Description;
                return new HtmlString(result + create + "</td>");
            }
        }
        else if (@meal.Description != null)
        {
            return new HtmlString(result + details + "</td>");
        }
        return new HtmlString("<td></td>");
    }
}


<table class="table" border="1">
    <tr>
        <th>
            @String.Empty
        </th>
        <th>
            @firstDay.ToString()
            <p>
                @pickedWeekMondayDate.ToString("dd")
            </p>
        </th>
        <th>
            @secondDay.ToString()
            <p>
                @pickedWeekTuesdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @thirdDay.ToString()
            <p>
                @pickedWeekWednesdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @fourthDay.ToString()
            <p>
                @pickedWeekThursdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @fifthDay.ToString()
            <p>
                @pickedWeekFridayDate.ToString("dd")
            </p>
        </th>
        <th>
            @sixthDay.ToString()
            <p>
                @pickedWeekSaturdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @seventhDay.ToString()

            <p>
                @pickedWeekSundayDate.ToString("dd")
            </p>
        </th>
    </tr>

    @{
        MealDTO[] breakfasts = (MealDTO[])ViewBag.Meals[0];
        <tr>
            <td>Breakfast</td>
            @foreach (MealDTO meal in (MealDTO[])breakfasts)
            {
                @cell(meal)
            }
        </tr>
        MealDTO[] lunchs = (MealDTO[])ViewBag.Meals[1];
        <tr>
            <td>Lunch</td>
            @foreach (MealDTO meal in (MealDTO[])lunchs)
            {
                @cell(meal)
            }
        </tr>
        MealDTO[] diners = (MealDTO[])ViewBag.Meals[2];
        <tr>
            <td>Dinner</td>
            @foreach (MealDTO meal in (MealDTO[])diners)
            {
                @cell(meal)
            }
        </tr>
    }

</table>
@{
    var clientId = Utility.getClientIdForProgramId(programIdFromUri);
}
<p>

    @Html.ActionLink("Back to client's programs", "AllProgramsOfClient", "Program", new { clientId = clientId }, null)
</p>