TrainerClientADOnet/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TrainerClientADOnet.Models;
using TrainerClientADOnet.Models.DAO;
using TrainerClientADOnet.Models.DTO;
using TrainerClientADOnet.Utilities;
using PagedList;

namespace TrainerClientADOnet.Controllers
{
    [Authorize(Roles = Utility.TRAINER_ROLE)]
    public class ClientController : Controller
    {
        ClientDAO clientDAO = new ClientDAO();
        ProgramDAO programDAO = new ProgramDAO();
        UserRoleDAO userRoleDAO = new UserRoleDAO();

        private static readonly Regex sWhitespace = new Regex(@"\s+");
        public static string ReplaceWhitespace(string input, string replacement)   // ReplaceWhitespace(,sWhitespace)
        {
            return sWhitespace.Replace(input, replacement);
        }

        //OK
        // GET: Client
        public ActionResult Index( int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<ClientDTO> pro = null;
            List<ClientDTO> clients  = clientDAO.GetAll();
            pro = clients.ToPagedList(pageIndex, pageSize);
            return View(pro);
        }

        //OK
        // GET: Client/Details/5
        public ActionResult Details(string id)
        {
            var clients = clientDAO.GetAll();
            char[] charsToTrim = { ' ' };
            var client = clients.FirstOrDefault(c => c.Id.TrimEnd(charsToTrim).Equals(id));
            if (client != null)
            {
                return View(client);
            }
            else
            {
                return View("Error");
            }
        }

        //OK
        // GET: Client/Create
        public ActionResult Create()
        {
            ClientUserRoleDTO client = new ClientUserRoleDTO();
            client.RegistrationDate = DateTime.Now; 

            client.Email = "@mailinator.com";
            client.PasswordHash = "Teodora!7";
            client.EmailConfirmed = false;
            client.PhoneNumberConfirmed = false;
            client.TwoFactorEnabled = false;
            client.LockoutEnabled = false;
            client.AccessFailedCount = 0;
            client.UserName = "@mailinator.com";
            return View(client);
        }

        //ok
        // POST: Client/Create
        [HttpPost]
        public async Task<ActionResult> Create(ClientUserRoleDTO client)
        {
            var errors = ModelState
.Where(x => x.Value.Errors.Count > 0)
.Select(x => new { x.Key, x.Value.Errors })
.ToArray();
            if (ModelState.IsValid)
            {
                try
                {
                    string roleId = GetRoleIdOfClient();
                    string email = client.Email;
                    string password = client.Password;
                    string userName = email;
                   // string roleName = collection["Name";
                    bool emailConfirmed = false;
                    bool phoneNumberConfirmed = false;
                    bool twoFactorEnabled = false;
                    bool lockoutEnabled = false;
                    int accesFailedCount = 0;
                    //ovo gore dobro pokupi i sada trebam da ovog klijenta posaljem da kreira Identity i onda taj vraceni ID->upisem tog korisnika!!!
                    //////////////////////
                    string firstName = client.FirstName;
                    string lastName = client.LastName;
                    DateTime registrationDate = client.RegistrationDate;
                    DateTime dateOfBirth = client.DateOfBirth;
                    string description = client.Description;
                  
                    //////////////////////////
                   await clientDAO.Create(firstName, lastName, dateOfBirth, registrationDate, roleId, email, userName, password, emailConfirmed, phoneNumberConfirmed, twoFactorEnabled, lockoutEnabled, accesFailedCount, description);

                    

                    return RedirectToAction("Index");
                    //return RedirectToAction("Details", new { id = id });


                }
                catch(Exception e)
                {
                    return View("Error");
                }
            }
            else
            {
                return View("Create");
            }
        }

        private string GetRoleIdOfClient()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var clientRole = context.Roles.Where(d => d.Name.Equals(Utility.CLIENT_ROLE)).FirstOrDefault();
            return clientRole.Id;
        }

        //OK
        // GET: Client/Edit/5
        public ActionResult Edit(string id)
        {
            var clients = clientDAO.GetAll();
            clients.ForEach(c => Regex.Replace(c.Id, @"s", ""));
                   char[] charsToTrim = {' '};
            var client = clients.FirstOrDefault(c => c.Id.TrimEnd(charsToTrim).Equals(id));
            if (client != null)
            {
                return View(client);
            }
            else
            {
                return View("Error");
            }
        }

        //ok
        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                string firstName = collection["FirstName"];
                string lastName = collection["LastName"];
                DateTime birthDate = DateTime.Parse(collection["DateOfBirth.Date"]);
                DateTime registrationDate = DateTime.Parse(collection["RegistrationDate.Date"]);
                string description = collection["Description"];
                int number = clientDAO.Edit(id, firstName, lastName, birthDate, registrationDate, description);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Client/Delete/5
        public ActionResult Delete(string id)
        {
            var clients = clientDAO.GetAll();

            char[] charsToTrim = { ' ' };
            var client = clients.FirstOrDefault(c => c.Id.TrimEnd(charsToTrim).Equals(id));

            if (client != null)
            {
                return View(client);
            }
            else
            {
                return View("Error");
            }
        }

        //ok
        // POST: Client/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                userRoleDAO.Delete(id); //brisanje iz Identity-ja
                clientDAO.Delete(id);  //brisanje iz baze

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

    }
}

TrainerClientADOnet/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainerClientADOnet.Models.DAO;
using TrainerClientADOnet.Models.DTO;
using TrainerClientADOnet.Utilities;
using PagedList;

namespace TrainerClientADOnet.Controllers
{
    public class ProgramController : Controller
    {
        ProgramDAO programDAO = new ProgramDAO();
        GoalTypeDAO goalTypeDAO = new GoalTypeDAO();
        ProgramGoalTypeDAO programGoalTypeDAO = new ProgramGoalTypeDAO();

        //OK
        // GET: Program/Details/5
        public ActionResult Details(int id)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                program.ProgramType = Utility.setProgramType(program.IsMeal);
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

       
        //OK
        // GET: Program/Edit/5
        public ActionResult Edit(int id, int? clientId)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

        //todo:edit program
        // POST: Program/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, int? clientId, FormCollection collection)
        {
            var program = programGoalTypeDAO.GetById(id);
            try
            {
                //string name = collection["Name"];
               // int number = programDAO.Edit(id, name);

                //return RedirectToAction("Index");
                return RedirectToAction("AllProgramsOfClient", new { clientId = program.ClientId });
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Program/Delete/5
        public ActionResult Delete(int id, int? clientId)
        {
            var program = programGoalTypeDAO.GetById(id);
            if (program != null)
            {
                program.ProgramType = Utility.setProgramType(program.IsMeal);
                return View(program);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Program/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, int? clientId, FormCollection collection)
        {
            var program = programGoalTypeDAO.GetById(id);
            try
            {
                programDAO.Delete(id);

                return RedirectToAction("AllProgramsOfClient", new { clientId = program.ClientId });
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Program/AllProgramsOfClient/5
        public ActionResult AllProgramsOfClient(string clientId, int? page, int? goalTypeId)   //za slucaj da ide na 2.stranicu da i dalje zna da je uljucena pretraga iz combo boxa
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<ProgramGoalTypeDTO> pro = null;
            List<ProgramGoalTypeDTO> programs = programGoalTypeDAO.GetAllOfClient(clientId);
           // List<ProgramGoalTypeDTO> selectedPrograms=programs.Where(p=>p.Is)
            pro = programs.ToPagedList(pageIndex, pageSize);
            return View(pro);
        }

        //OK
        // GET: Client/CreateProgramForClient/5
        public ActionResult CreateProgramForClient(string clientId)
        {
            ProgramDTO program = new ProgramDTO();
            program.ClientId = clientId;
            program.StartTime = DateTime.Today;  
            program.EndTime = DateTime.Today;
            ViewBag.goalsItems = goalTypeDAO.GetAll();
            return View(program);
        }

        //ok
        // POST: Client/CreateProgramForClient/5
        [HttpPost]
        public ActionResult CreateProgramForClient(string clientId, FormCollection collection)  
        {
            try
            {
                
                int goalTypeId = int.Parse(collection["GoalTypeId"]);    
                DateTime startTime = DateTime.Parse(collection["StartTime.Date"]);
                DateTime endTime = DateTime.Parse(collection["EndTime.Date"]);
                string description = collection["Description"];
                bool isMeal= bool.Parse(collection["IsMeal"]);

                int id = programDAO.Create(clientId, goalTypeId, startTime, endTime, description, isMeal); 

               // return RedirectToAction("AllProgramsOfClient", new { clientId=client_id });
                return RedirectToAction("Details", new { id = id });   
            }
            catch
            {
                return View("Error");
            }
        }

    }
}

TrainerClientADOnet/Views/Client/AllPrograms.cshtml
@model IEnumerable<TrainerClientADOnet.Models.DTO.ProgramDTO>

@{
    ViewBag.Title = "AllPrograms";
}

<h2>All Programs for selected client</h2>

@*if (Model.Any()) { }*@
<p>
    <!-- Html.ActionLink("Create New Program", "CreateProgramForClient", new { id = Model.ElementAtOrDefault(1).ClientId })    -->
    @Html.ActionLink("Create New Program", "CreateProgramForClient", new { client_id = Url.RequestContext.RouteData.Values["id"] })
</p>

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.GoalTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.GoalTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

TrainerClientADOnet/Views/Client/Create.cshtml
@model TrainerClientADOnet.Models.DTO.ClientUserRoleDTO


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClientUserRoleDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
@*
        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>
*@
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
@*
        <div class="form-group">
            @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailConfirmed)
                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PhoneNumberConfirmed)
                    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TwoFactorEnabled)
                    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LockoutEnabled)
                    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
    *@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@*
@{ 
    //uri
    Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri);
    var programIdFromUri = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim();
    var monday = ViewBag.SelectedMonday;
    var sunday = monday.AddDays(6);
}
<div>
    @Html.ActionLink("TrainingPlanForProgram", "TrainingPlanForProgram", new { programId = programIdFromUri, monday  = monday, sunday=sunday })
</div>
*@
<div>
    @Html.ActionLink("Back to clients", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrainerClientADOnet/Views/Client/Delete.cshtml
@model TrainerClientADOnet.Models.DTO.ClientDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TrainerClientADOnet/Views/Client/Details.cshtml
@model TrainerClientADOnet.Models.DTO.ClientDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClientDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id.Trim() }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TrainerClientADOnet/Views/Client/Index.cshtml
@* @model IEnumerable<TrainerClientADOnet.Models.DTO.ClientDTO>*@
@model PagedList.IPagedList<TrainerClientADOnet.Models.DTO.ClientDTO>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
}

<h2>Clients</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].RegistrationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = HttpUtility.UrlDecode(item.Id).Trim() }, null) |
                @Html.ActionLink("Details", "Details", new { id = HttpUtility.UrlDecode(item.Id).Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = HttpUtility.UrlDecode(item.Id).Trim() }, null)  |||
                @Html.ActionLink("Programs", "AllProgramsOfClient", "Program", new { clientId = HttpUtility.UrlDecode(item.Id).Trim() }, null)
            </td>
        </tr>
    }

</table>

<style>
    .ul.pagination {
        display: inline-block;
        padding: 0;
        margin: 0;
    }

    ul.pagination li {
        display: inline;
    }

        ul.pagination li a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
        }

            ul.pagination li a.active {
                background-color: #4CAF50;
                color: white;
            }

            ul.pagination li a:hover:not(.active) {
                background-color: #ddd;
            }
</style>


<div id="container" style="margin-left: 20px">
    <p></p>
    <p></p>
    <div class="pagination" style="margin-left: 400px">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount   @Html.PagedListPager(Model, page => @Url.Action("Index", "Client"));
        @*.Replace("i", clientID));*@
        @*of @Model.PageCount @PagedList.Mvc.HtmlHelper.PagedListPager(Html, Model, page => Url.Action("AllProgramsOfClient", "Program", new { clientId = clientID }, new { page })) *@


    </div>
</div>