TrainerClientADOnet/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainerClientADOnet.Models.DAO;
using TrainerClientADOnet.Models.DTO;
using TrainerClientADOnet.Utilities;

namespace TrainerClientADOnet.Controllers
{
    public class TrainingController : Controller
    {
        TrainingDAO trainingDAO = new TrainingDAO();
        public const int NUMBER_OF_TRAINING_ROWS = 14;  //8-9, 9-10, ..., 20-21, 21-22   //22-8=14  mogucih satnica u toku dana
        public const int NUMBER_OF_DAYS = 7;
        static TrainingDTO[][] trainingDescriptions = new TrainingDTO[NUMBER_OF_TRAINING_ROWS][];
        static ClientTrainingDTO[][] trainerTrainingDescriptions = new ClientTrainingDTO[NUMBER_OF_TRAINING_ROWS][];

        //ok: za klijenta
        // GET: Training/Details/5
        [Authorize(Roles = Utility.CLIENT_ROLE)]
        public ActionResult Details(int id, DateTime monday)
        {
            var training = trainingDAO.GetById(id);
            if (training != null)
            {
                ViewBag.SelectedMonday = monday;
                return View(training);
            }
            else
            {
                return View("Error");
            }
        }

        //OK
        // GET: Training/Create
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Create(int id, DateTime monday, DateTime startTime, DateTime endTime, int trainingTypeId, int programId)
        {
            TrainingDTO training = GetById(id);  
            if (training != null)
            {
                ViewBag.SelectedMonday = monday;
                return View(training);
            }
            else
            {
                return View("Error");
            }
        }

        // GET: Training/CreateWithoutClientAndProgram
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult CreateWithoutClientAndProgram(int id, DateTime monday, DateTime startTime, DateTime endTime, int trainingTypeId)
        {
            TrainingDTO training = GetById(id);
            if (training != null)
            {
                ViewBag.SelectedMonday = monday;
                training.TrainingTypeId = 2;
                return View(training);
            }
            else
            {
                return View("Error");
            }
        }
        // POST: Training/CreateWithoutClientAndProgram
        [HttpPost]
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult CreateWithoutClientAndProgram( DateTime monday, FormCollection collection)
        {
            try
            {
                int trainingTypeId = int.Parse(collection["TrainingTypeId"]);
                DateTime startTimeWeek = DateTime.Parse(collection["StartTime"]);
                DateTime endTime;
                string description = collection["Description"];
                int duration = int.Parse(collection["Duration"]);
                int recurring = int.Parse(collection["Recurring"]);


                //ovo sedmicno gleda
                for (int j = 1; j <= recurring; j++)
                {
                    DateTime startTime = startTimeWeek;
                    //U istom danu da nadodaje trening
                    if (duration >= 1)
                    {
                        for (int i = 1; i <= duration; i++)
                        {
                            endTime = startTime.AddHours(1);
                            int newId = trainingDAO.CreateWithoutClientAndProgram( trainingTypeId, startTime, endTime, description);
                            startTime = startTime.AddHours(1);
                        }

                    }
                    startTimeWeek = startTimeWeek.AddDays(7);
                }

                DateTime sunday = monday.AddDays(6);
                return RedirectToAction("AllTrainerTrainings", new {  monday = monday });
            }
            catch
            {
                return View("Error");
            }
        }
        //OK - treba da trening potrazi po Id-ju u nizu trainingDescriptions[][] i kada ga nadje, treba ga vratiti
        public static TrainingDTO GetById(int id)
        {
            for(int i = 0; i < NUMBER_OF_TRAINING_ROWS; i++) 
            { 
                for (int j = 0; j < NUMBER_OF_DAYS; j++)
                {
                    if (((TrainingDTO)(trainingDescriptions[i][j])).Id == id) { return trainingDescriptions[i][j]; }
                }
            }
            return null;
        }

        //OK
        // POST: Training/Create
        [HttpPost]
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Create(int programId, DateTime monday, FormCollection collection)
        {
            try
            {
                int trainingTypeId = int.Parse(collection["TrainingTypeId"]);
                DateTime startTimeWeek = DateTime.Parse(collection["StartTime"]);
                DateTime endTime;
                string description = collection["Description"];
                int duration = int.Parse(collection["Duration"]);
                int recurring = int.Parse(collection["Recurring"]);


                //ovo sedmicno gleda
                for (int j = 1; j <= recurring; j++)
                {
                    DateTime startTime = startTimeWeek;
                    //U istom danu da nadodaje trening
                    if (duration >= 1)
                    {
                        for (int i = 1; i <= duration; i++)
                        {
                            endTime = startTime.AddHours(1);
                            int newId = trainingDAO.Create(programId, trainingTypeId, startTime, endTime, description);
                            startTime = startTime.AddHours(1);
                        }

                    }
                    startTimeWeek = startTimeWeek.AddDays(7);
                }

                DateTime sunday = monday.AddDays(6);
                return RedirectToAction("TrainingPlanForProgram", new { programId = programId, monday = monday });
            }
            catch
            {
                return View("Error");
            }
        }

        //OK
        // GET: Training/Edit/5
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Edit(int id, DateTime monday, DateTime startTime, DateTime endTime)
        {

            var training = trainingDAO.GetById(id);
            if (training != null)
            {
                ViewBag.SelectedMonday = monday;
                return View(training);
            }
            else
            {
                return View("Error");
            }
        }
       
        // POST: Training/Edit/5
        [HttpPost]
        [Authorize(Roles = Utility.TRAINER_ROLE)]
        public ActionResult Edit(int id, DateTime monday, FormCollection collection)
        {
            try
            {
                TrainingDTO trainingBeforeEditing = trainingDAO.GetById(id);
                int programID = int.Parse(collection["ProgramId"]);
                int trainingTypeId = int.Parse(collection["TrainingTypeId"]);
                DateTime startTime = DateTime.Parse(collection["StartTime"]);
                //DateTime endTime = DateTime.Parse(collection["EndTime"]);
                string description = collection["Description"];
                int newDuration = int.Parse(collection["Duration"]);

                List<TrainingDTO> trainings = trainingDAO.getTrainingsByDescriptionTypeDay(trainingBeforeEditing.ProgramId, trainingBeforeEditing.Description, trainingBeforeEditing.StartTime, trainingBeforeEditing.TrainingTypeId);
                int previousDuration= trainings.Count();
                trainings.OrderBy(t=>t.StartTime.Hour); //sortiram treninge po redu
                
                
                if (newDuration > previousDuration) //dodajem novi trening/nove treninge
                {
                    DateTime lastStartTime = trainings.Last().StartTime; //od zadnjeg nejgovo startno vrijeme
                    DateTime lastEndTime = lastStartTime.AddHours(1);
                    trainings.ForEach(training => trainingDAO.Edit(training.Id, trainingTypeId, description));
                    for (int i = newDuration - previousDuration; i > 0; --i)
                    {
                        lastStartTime = lastStartTime.AddHours(1);
                        lastEndTime = lastEndTime.AddHours(1);
                        trainingDAO.Create(programID, trainingTypeId, lastStartTime, lastEndTime, description);
                    }
                }
                else if (newDuration < previousDuration)
                {//brisem zadnji trening/zadnje treninge
                    TrainingDTO trainingForDelete = null;
                    trainings.ForEach(training => trainingDAO.Edit(training.Id, trainingTypeId, description));
                    for (int i = previousDuration - newDuration; i > 0; --i)
                    {
                        trainingForDelete = trainings.Last();
                        trainings.Remove(trainingForDelete);
                        trainingDAO.Delete(trainingForDelete.Id);
                    }
                }
                else
                {
                    //za svaki trening iznad, editujem preostala polja: TIP TRENINGA i OPIS
                    trainings.ForEach(training => trainingDAO.Edit(training.Id, trainingTypeId, description));
                }

                //int number = trainingDAO.Edit(id, trainingTypeId, startTime, endTime ,description);
                DateTime sunday = monday.AddDays(6);
                return RedirectToAction("TrainingPlanForProgram", new { programId = programID, monday = monday, sunday = sunday });
            }
            catch
            {
                return View("Error");
            }
        }

        

TrainerClientADOnet/Views/Training/AllTrainerTrainings.cshtml
@model TrainerClientADOnet.Models.DTO.ClientTrainingDTO
@using TrainerClientADOnet.Models.DTO;
@using TrainerClientADOnet.Utilities;
<head>
    @section Scripts{
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
        <script type="text/javascript">

            function copyToClipboard(message) {
                var msg = message;
                console.log(msg);
                //use msg now
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val(msg).select();
                document.execCommand("copy");
                $temp.remove();
            };
        </script>
    }
</head>
@{
    ViewBag.Title = "AllTrainerTrainings";
}
<h2>Trainings of all clients</h2>
@{
    //konstante u headeru tabele:
    var firstDay = DayOfWeek.Monday;
    var secondDay = DayOfWeek.Tuesday;
    var thirdDay = DayOfWeek.Wednesday;
    var fourthDay = DayOfWeek.Thursday;
    var fifthDay = DayOfWeek.Friday;
    var sixthDay = DayOfWeek.Saturday;
    var seventhDay = DayOfWeek.Sunday;
    //zbog promjene sedmice:
    var pickedWeekMondayDate = ViewBag.SelectedMonday;
    var pickedWeekTuesdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(1);
    var pickedWeekWednesdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(2);
    var pickedWeekFridayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(4);
    var pickedWeekThursdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(3);
    var pickedWeekSaturdayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(5);
    var pickedWeekSundayDate = ((DateTime)ViewBag.SelectedMonday).AddDays(6);
    //za pomjeranje sedmice:
    var previousMonday = Utility.previousMonday(ViewBag.SelectedMonday);
    var nextMonday = Utility.nextMonday(ViewBag.SelectedMonday);
}

@* Dugmad za prebacivanje na sledecu i prethodnu sedmicu *@
<button type="button" onclick="location.href='@Url.Action("AllTrainerTrainings", "Training", new { monday = previousMonday })'">
    <img alt="Previous" title="Previous week" src="~/Images/Button/left.png" style="width: 15px; height:20px">
</button>
<button type="button" onclick="location.href='@Url.Action("AllTrainerTrainings", "Training", new { monday  = nextMonday })'">

    <img alt="Next" title="Next week" src="~/Images/Button/right.png" style="width: 15px; height:20px">
</button>

@* Prikaz izabrane sedmice *@
@if (@pickedWeekMondayDate.ToString("MMMM").Equals(@pickedWeekSundayDate.ToString("MMMM")))
{//prikaz: July 20 - 27, 20
    <h3>
        @pickedWeekMondayDate.ToString("MMMM") @pickedWeekMondayDate.ToString("dd") - @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yy")
    </h3>
}
else //prikaz: July 27 - August 02, 20
{
    if (@pickedWeekMondayDate.ToString("yy").Equals(@pickedWeekSundayDate.ToString("yy")))
    {
        <h3>
            @pickedWeekMondayDate.ToString("MMMM")  @pickedWeekMondayDate.ToString("dd") - @pickedWeekSundayDate.ToString("MMMM") @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yy")
        </h3>
    }
    else //prikaz: December 27, 2020 - Januar 02, 2021
    {
        <h3>
            @pickedWeekMondayDate.ToString("MMMM")  @pickedWeekMondayDate.ToString("dd"), @pickedWeekMondayDate.ToString("yyyy") - @pickedWeekSundayDate.ToString("MMMM") @pickedWeekSundayDate.ToString("dd"), @pickedWeekSundayDate.ToString("yyyy")
        </h3>

    }
}

@functions{
    public HtmlString cell(ClientTrainingDTO training)
    {
        String result = "<td>";
        var monday = ViewBag.SelectedMonday;
        if (training.Id > 0)
        {
            if (Utility.IsWrittenAlreadyThisTraining(training.ProgramId, training.Description, training.StartTime, training.TrainingTypeId)) //ako je trening sa ovim osobinama, ali MANJEG SATA vec upisan, onda nista ne prikazi sem boje
            {//Ako je u celiju tabele ovaj trening vec upisan i ima Description i Edit u polju, onda ne treba vise pisati! Treninzi ispod ce samo biti obojeni kao i taj iznad.
                return new HtmlString("<td style=\"background-color:#ffebcc; \">" + "</td>"); //todo: dodam i delete dugme ako je zadnji trening na spisku (zbog edit forme nema smisla da se brise neki u sredini)

            }
            result = "<td style=\"background-color:#ffebcc; \">" + "<b>" + @training.FullName + "</b>" + @training.Description;
            //TODO: slati flag da zna je li vraca ovdje ili u onu drugu formu
            String edit = (@Html.ActionLink("Edit", "Edit", new { id = training.Id, monday = monday, startTime = training.StartTime, endTime = training.EndTime, trainingTypeId = training.TrainingTypeId, programId = training.ProgramId })).ToString();
            var description = @training.Description;
            var image = @Url.Content("~/Images/Button/cb5.png");
            String copy = " <button type=\"button\" id=\"copyButton\" runat=\"server\" onClick=\" copyToClipboard(\'" + description + "\'); \" style=\"background-color: Transparent; border: none;\" >  <img src=\"" + image + "\" style=\"height:20px;width:15px;color:blue\" title=\"Copy to clipboard description\" /> </button>"; // @* *@

            result = result + edit + copy;
        }
        else
        {
            String create = (@Html.ActionLink("+", "CreateWithoutClientAndProgram", new { id = training.Id, monday = monday, startTime = training.StartTime, endTime = training.EndTime, trainingTypeId = training.TrainingTypeId }, new { @class = "btnCreate" })).ToString();
        
             return new HtmlString(result + create + "</td>");
        }
        return new HtmlString(result + "</td>");
    }
}


<table class="table" border="1">
    <tr>
        <th>
            @String.Empty
        </th>
        <th>
            @firstDay.ToString()
            <p>
                @pickedWeekMondayDate.ToString("dd")
            </p>
        </th>
        <th>
            @secondDay.ToString()
            <p>
                @pickedWeekTuesdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @thirdDay.ToString()
            <p>
                @pickedWeekWednesdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @fourthDay.ToString()
            <p>
                @pickedWeekThursdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @fifthDay.ToString()
            <p>
                @pickedWeekFridayDate.ToString("dd")
            </p>
        </th>
        <th>
            @sixthDay.ToString()
            <p>
                @pickedWeekSaturdayDate.ToString("dd")
            </p>
        </th>
        <th>
            @seventhDay.ToString()
            <p>
                @pickedWeekSundayDate.ToString("dd")
            </p>
        </th>
    </tr>

    @{
        ClientTrainingDTO[] eightToNine = (ClientTrainingDTO[])ViewBag.Tranings[0];
        <tr>
            <td><b>8h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])eightToNine)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] nineToTen = (ClientTrainingDTO[])ViewBag.Tranings[1];
        <tr>
            <td><b>9h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])nineToTen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] tenToEleven = (ClientTrainingDTO[])ViewBag.Tranings[2];
        <tr>
            <td><b>10h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])tenToEleven)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] elevenToTwelve = (ClientTrainingDTO[])ViewBag.Tranings[3];
        <tr>
            <td><b>11h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])elevenToTwelve)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] twelveToThirteen = (ClientTrainingDTO[])ViewBag.Tranings[4];
        <tr>
            <td><b>12h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])twelveToThirteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] thirteenToFourteen = (ClientTrainingDTO[])ViewBag.Tranings[5];
        <tr>
            <td><b>13h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])thirteenToFourteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] fourteenToFifthteen = (ClientTrainingDTO[])ViewBag.Tranings[6];
        <tr>
            <td><b>14h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])fourteenToFifthteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] fifthteenToSixteen = (ClientTrainingDTO[])ViewBag.Tranings[7];
        <tr>
            <td><b>15h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])fifthteenToSixteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] sixteenToSeventeen = (ClientTrainingDTO[])ViewBag.Tranings[8];
        <tr>
            <td><b>16h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])sixteenToSeventeen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] seventeenToEighteen = (ClientTrainingDTO[])ViewBag.Tranings[9];
        <tr>
            <td><b>17h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])seventeenToEighteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] eighteenToNineteen = (ClientTrainingDTO[])ViewBag.Tranings[10];
        <tr>
            <td><b>18h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])eighteenToNineteen)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] nineteenToTwenty = (ClientTrainingDTO[])ViewBag.Tranings[11];
        <tr>
            <td> <b> 19h </b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])nineteenToTwenty)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] twentyToTwentyone = (ClientTrainingDTO[])ViewBag.Tranings[12];
        <tr>
            <td> <b>20h </b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])twentyToTwentyone)
            {
                @cell(training)
            }
        </tr>

        ClientTrainingDTO[] twentyoneToTwentytwo = (ClientTrainingDTO[])ViewBag.Tranings[13];
        <tr>
            <td> <b> 21h</b></td>
            @foreach (ClientTrainingDTO training in (ClientTrainingDTO[])twentyoneToTwentytwo)
            {
                @cell(training)
            }
        </tr>
    }

</table>

TrainerClientADOnet/Views/Training/Create.cshtml
@model TrainerClientADOnet.Models.DTO.TrainingDTO
@using TrainerClientADOnet.Utilities;
@using TrainerClientADOnet.Controllers;

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@{
    Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri);
    DateTime StartTime = DateTime.Parse(HttpUtility.ParseQueryString(uri.Query).Get("startTime").Trim());
    int programId = int.Parse(HttpUtility.ParseQueryString(uri.Query).Get("programId"));
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Training</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramId)


    <div class="form-group">
        @Html.LabelFor(model => model.TrainingTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TrainingTypeId, Utility.returnSelectListOfTrainingTypes(), " Select training type ", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TrainingTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
                    @readonly = true@*, disabled = "disabled"*@}
})
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Duration (hours)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Duration", "1", htmlAttributes: new { @type = "number", @class = "form-control", @min = "1", @max = Utility.GetMaxTrainingDurationTimeCreate(StartTime, programId) })
            @Html.ValidationMessage("Duration", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Recurring (weeks in same time)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Recurring", "1", htmlAttributes: new { @type = "number", @class = "form-control", @min = "1", @max = Utility.GetMaxTrainingReccuringTimeCreate(StartTime, programId) })
            @Html.ValidationMessage("Recurring", "", new { @class = "text-danger" })
        </div>
    </div>

    @*Validator.Range(min, max [, error message])*@
    @*
        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>
    *@
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
@{
    //uri
    
    var programIdFromUri = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim();
    DateTime monday = ViewBag.SelectedMonday;
    var sunday = monday.AddDays(6);

}
<div>
    @Html.ActionLink("Back to List", "TrainingPlanForProgram", new { programId = programIdFromUri, monday=monday, sunday=sunday }, null)

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrainerClientADOnet/Views/Training/Delete.cshtml
@model TrainerClientADOnet.Models.DTO.TrainingDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainingDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Edit", "Index")
        </div>
    }
</div>

TrainerClientADOnet/Views/Training/Details.cshtml
@model TrainerClientADOnet.Models.DTO.TrainingDTO

<div>
    <h4>TrainingDTO</h4>
    <hr />
    <dl class="dl-horizontal">

        @*
        <dt>
            @Html.DisplayNameFor(model => model.TrainingTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingTypeId)
        </dd>
            *@
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id, startTime=Model.StartTime, endTime=Model.EndTime}) | *@
        @{Uri uri = new Uri(HttpContext.Current.Request.Url.AbsoluteUri); }
        @Html.ActionLink("Back to List", "TrainingPlanForProgram", new { programId = HttpUtility.ParseQueryString(uri.Query).Get("programId").Trim() }, null)
</p>